name: architecture_proposal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # architecture_proposal_domain:
  #   path: packages/architecture_proposal_domain
  architecture_proposal_data:
    path: packages/architecture_proposal_data
  architecture_proposal_ui:
    path: packages/architecture_proposal_ui
  provider: ^6.0.5
  go_router: ^9.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
