name: architecture_proposal_data
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: ^3.0.3

dependencies:
  architecture_proposal_domain:
    path: ../architecture_proposal_domain
  rxdart: ^0.27.7
    
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
